// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7MlneD-NF0mwwUo7o6cC8v-WnSEVVxfY',
    appId: '1:1037118513656:web:0cfaceee220ce7bb99360d',
    messagingSenderId: '1037118513656',
    projectId: 'first-59545',
    authDomain: 'first-59545.firebaseapp.com',
    storageBucket: 'first-59545.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkhKAx6vMe-z2w6Db_wXp-5t3jfQeHkh0',
    appId: '1:1037118513656:android:588a3ded65ae591a99360d',
    messagingSenderId: '1037118513656',
    projectId: 'first-59545',
    storageBucket: 'first-59545.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCex3ObJ21fP2FqyC7pS2B2wWG2r7TuITc',
    appId: '1:1037118513656:ios:7a4df6c677c6434c99360d',
    messagingSenderId: '1037118513656',
    projectId: 'first-59545',
    storageBucket: 'first-59545.appspot.com',
    iosBundleId: 'com.example.mysqplWithFlutter',
  );
}
